name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # List files to verify directory structure
      - name: List project files
        run: ls -R

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the React app
      - name: Build the React app
        run: npm run build
